# Generated by Django 5.1.7 on 2025-03-24 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_recipeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimage',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='recipe_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='ledger.recipe'),
        ),
    ]
