# Generated by Django 5.1.7 on 2025-03-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_remove_recipeimage_recipe_recipeimage_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='recipe_image',
            new_name='recipe',
        ),
    ]
